{"name": "Login to OrangeHRM with given parameters -- @1.4 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=128.0.6613.120)\nStacktrace:\n0   chromedriver                        0x000000010311b998 cxxbridge1$str$ptr + 1887096\n1   chromedriver                        0x0000000103113e00 cxxbridge1$str$ptr + 1855456\n2   chromedriver                        0x0000000102d18be0 cxxbridge1$string$len + 89508\n3   chromedriver                        0x0000000102d03dd4 cxxbridge1$string$len + 3992\n4   chromedriver                        0x0000000102d03b5c cxxbridge1$string$len + 3360\n5   chromedriver                        0x0000000102d01ef8 core::str::slice_error_fail::h6c488016ada29016 + 61108\n6   chromedriver                        0x0000000102d02468 core::str::slice_error_fail::h6c488016ada29016 + 62500\n7   chromedriver                        0x0000000102d0899c cxxbridge1$string$len + 23392\n8   chromedriver                        0x0000000102d00fec core::str::slice_error_fail::h6c488016ada29016 + 57256\n9   chromedriver                        0x0000000102d03878 cxxbridge1$string$len + 2620\n10  chromedriver                        0x0000000102d01ef8 core::str::slice_error_fail::h6c488016ada29016 + 61108\n11  chromedriver                        0x0000000102d02468 core::str::slice_error_fail::h6c488016ada29016 + 62500\n12  chromedriver                        0x0000000102cf9064 core::str::slice_error_fail::h6c488016ada29016 + 24608\n13  chromedriver                        0x0000000102d00fec core::str::slice_error_fail::h6c488016ada29016 + 57256\n14  chromedriver                        0x0000000102d00990 core::str::slice_error_fail::h6c488016ada29016 + 55628\n15  chromedriver                        0x0000000102d004ec core::str::slice_error_fail::h6c488016ada29016 + 54440\n16  chromedriver                        0x0000000102d1aad8 cxxbridge1$string$len + 97436\n17  chromedriver                        0x0000000102cf36b0 core::str::slice_error_fail::h6c488016ada29016 + 1644\n18  chromedriver                        0x0000000102cf32b0 core::str::slice_error_fail::h6c488016ada29016 + 620\n19  chromedriver                        0x0000000102d86b80 cxxbridge1$string$len + 539972\n20  chromedriver                        0x0000000102d51a08 cxxbridge1$string$len + 322508\n21  chromedriver                        0x0000000102d5266c cxxbridge1$string$len + 325680\n22  chromedriver                        0x00000001030e2058 cxxbridge1$str$ptr + 1651256\n23  chromedriver                        0x00000001030e698c cxxbridge1$str$ptr + 1669996\n24  chromedriver                        0x00000001030c71ec cxxbridge1$str$ptr + 1541068\n25  chromedriver                        0x00000001030e725c cxxbridge1$str$ptr + 1672252\n26  chromedriver                        0x00000001030b8800 cxxbridge1$str$ptr + 1481184\n27  chromedriver                        0x00000001031050f8 cxxbridge1$str$ptr + 1794776\n28  chromedriver                        0x0000000103105274 cxxbridge1$str$ptr + 1795156\n29  chromedriver                        0x0000000103113a9c cxxbridge1$str$ptr + 1854588\n30  libsystem_pthread.dylib             0x000000019a1fdf94 _pthread_start + 136\n31  libsystem_pthread.dylib             0x000000019a1f8d34 thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Login_steps.py\", line 12, in step_impl\n    context.driver = webdriver.Chrome()\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I launch the chrome browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=128.0.6613.120)\nStacktrace:\n0   chromedriver                        0x000000010311b998 cxxbridge1$str$ptr + 1887096\n1   chromedriver                        0x0000000103113e00 cxxbridge1$str$ptr + 1855456\n2   chromedriver                        0x0000000102d18be0 cxxbridge1$string$len + 89508\n3   chromedriver                        0x0000000102d03dd4 cxxbridge1$string$len + 3992\n4   chromedriver                        0x0000000102d03b5c cxxbridge1$string$len + 3360\n5   chromedriver                        0x0000000102d01ef8 core::str::slice_error_fail::h6c488016ada29016 + 61108\n6   chromedriver                        0x0000000102d02468 core::str::slice_error_fail::h6c488016ada29016 + 62500\n7   chromedriver                        0x0000000102d0899c cxxbridge1$string$len + 23392\n8   chromedriver                        0x0000000102d00fec core::str::slice_error_fail::h6c488016ada29016 + 57256\n9   chromedriver                        0x0000000102d03878 cxxbridge1$string$len + 2620\n10  chromedriver                        0x0000000102d01ef8 core::str::slice_error_fail::h6c488016ada29016 + 61108\n11  chromedriver                        0x0000000102d02468 core::str::slice_error_fail::h6c488016ada29016 + 62500\n12  chromedriver                        0x0000000102cf9064 core::str::slice_error_fail::h6c488016ada29016 + 24608\n13  chromedriver                        0x0000000102d00fec core::str::slice_error_fail::h6c488016ada29016 + 57256\n14  chromedriver                        0x0000000102d00990 core::str::slice_error_fail::h6c488016ada29016 + 55628\n15  chromedriver                        0x0000000102d004ec core::str::slice_error_fail::h6c488016ada29016 + 54440\n16  chromedriver                        0x0000000102d1aad8 cxxbridge1$string$len + 97436\n17  chromedriver                        0x0000000102cf36b0 core::str::slice_error_fail::h6c488016ada29016 + 1644\n18  chromedriver                        0x0000000102cf32b0 core::str::slice_error_fail::h6c488016ada29016 + 620\n19  chromedriver                        0x0000000102d86b80 cxxbridge1$string$len + 539972\n20  chromedriver                        0x0000000102d51a08 cxxbridge1$string$len + 322508\n21  chromedriver                        0x0000000102d5266c cxxbridge1$string$len + 325680\n22  chromedriver                        0x00000001030e2058 cxxbridge1$str$ptr + 1651256\n23  chromedriver                        0x00000001030e698c cxxbridge1$str$ptr + 1669996\n24  chromedriver                        0x00000001030c71ec cxxbridge1$str$ptr + 1541068\n25  chromedriver                        0x00000001030e725c cxxbridge1$str$ptr + 1672252\n26  chromedriver                        0x00000001030b8800 cxxbridge1$str$ptr + 1481184\n27  chromedriver                        0x00000001031050f8 cxxbridge1$str$ptr + 1794776\n28  chromedriver                        0x0000000103105274 cxxbridge1$str$ptr + 1795156\n29  chromedriver                        0x0000000103113a9c cxxbridge1$str$ptr + 1854588\n30  libsystem_pthread.dylib             0x000000019a1fdf94 _pthread_start + 136\n31  libsystem_pthread.dylib             0x000000019a1f8d34 thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Login_steps.py\", line 12, in step_impl\n    context.driver = webdriver.Chrome()\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725807643589, "stop": 1725807648278}, {"name": "When I open the OrangeHRM homepage", "status": "skipped", "start": 1725807648279, "stop": 1725807648279}, {"name": "And Enter username Admin and password admin234", "status": "skipped", "start": 1725807648279, "stop": 1725807648279}, {"name": "And Click login button", "status": "skipped", "start": 1725807648279, "stop": 1725807648279}, {"name": "Then User must successfully login to the Dashboard page", "status": "skipped", "start": 1725807648279, "stop": 1725807648279}], "parameters": [{"name": "username", "value": "Admin"}, {"name": "password", "value": "admin234"}], "start": 1725807643588, "stop": 1725807648279, "uuid": "296a67bb-7e60-4ab4-bcf3-96280f1ccb7e", "historyId": "0f3f2b8df142a099933515341b427bf6", "fullName": "OrangeHRM Login: Login to OrangeHRM with given parameters", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "OrangeHRM Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}